---
language: go
services:
  - docker
before_install:
  - docker pull lukaszgryglicki/devstats-tests
script:
  - docker run -ti lukaszgryglicki/devstats-tests
notifications:
  webhooks:
    - https://teststats.cncf.io:2982/hook
    - https://devstats.cncf.io:2982/hook
    - https://devstats.cd.foundation:2982/hook
    - https://devstats.graphql.org:2982/hook
