---
language: go
services:
  - docker
script:
  - docker run -ti lukaszgryglicki/devstats-test
notifications:
  webhooks:
    - https://teststats.cncf.io:2982/hook
    - https://devstats.cncf.io:2982/hook
    - https://devstats.cd.foundation:2982/hook
