FROM alpine AS builder
WORKDIR /builder
ADD devstats.tar .
ADD grafana-bins.tar .
FROM alpine
RUN apk add git bash postgresql-client xz curl vim zip
COPY --from=builder /builder/runq /usr/bin/
COPY --from=builder /builder/util_sql/exclude_bots.sql /etc/gha2db/util_sql/exclude_bots.sql
COPY --from=builder /builder/devel/db.sh /usr/bin/
ADD devstats-reports.tar .
