FROM postgres:18
MAINTAINER Josh Berkus <josh@berkus.org>

RUN export DEBIAN_FRONTEND=noninteractive \
    && echo 'APT::Install-Recommends "0";\nAPT::Install-Suggests "0";' > /etc/apt/apt.conf.d/01norecommend \
    && apt-get update -y \
    && apt-get upgrade -y \
    && apt-cache depends patroni \
         | sed -n -e 's/.* Depends: \(python3-.\+\)$/\1/p' \
         | grep -Ev '^python3-(sphinx|etcd|consul|kazoo|kubernetes)' \
         | xargs apt-get install -y \
             vim-tiny curl jq locales git python3-pip python3-wheel \
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8 \
    && apt-get install -y postgresql-18-hll \
    && pip3 install --break-system-packages --no-cache-dir setuptools \
    && pip3 install --break-system-packages --no-cache-dir 'patroni[kubernetes]' \
    && PGHOME=/home/postgres \
    && mkdir -p "$PGHOME" \
    && chown postgres "$PGHOME" \
    && sed -i "s|/var/lib/postgresql.*|$PGHOME:/bin/bash|" /etc/passwd \
    && chmod 775 "$PGHOME" \
    && chmod 664 /etc/passwd \
    && apt-get purge -y \
         git \
         python3-pip \
         python3-wheel \
         vim-tiny \
    && apt-get autoremove -y \
    && rm -rf \
         /var/lib/apt/lists/* \
         /root/.cache \
         /usr/share/doc/* \
         /usr/share/man/* \
         /usr/share/info/* \
         /usr/share/lintian/*

ADD images/patroni/entrypoint.sh /

EXPOSE 5432 8008
ENV LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 EDITOR=/usr/bin/editor
USER postgres
WORKDIR /home/postgres
CMD ["/bin/bash", "/entrypoint.sh"]

