FROM golang:1.13 AS builder
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y ca-certificates openssh-client git curl make
RUN go get -u github.com/cncf/devstatscode
WORKDIR /go/src/github.com/cncf/devstatscode
ADD devstats.tar .
ADD devstatscode.tar .
ADD devstats-docker-images.tar .
ADD grafana-bins.tar .
RUN cp replacer patches/patch.sh /usr/bin/
RUN patch.sh testsrv teststats.cncf.io 'kubernetes prometheus opentracing fluentd linkerd grpc coredns containerd rkt cni envoy jaeger notary tuf rook vitess nats opa spiffe spire cloudevents telepresence helm openmetrics harbor etcd tikv cortex buildpacks falco dragonfly virtualkubelet kubeedge brigade crio networkservicemesh openebs opentelemetry thanos flux intoto strimzi kubevirt longhorn chubaofs keda smi argo volcano cncf all opencontainers istio knative linux zephyr sam azf riff fn openwhisk openfaas graphql graphqljs graphiql expressgraphql graphqlspec spinnaker tekton jenkins jenkinsx allcdf cii prestodb'
RUN make -f ./images/Makefile.minimal dockerinstall
FROM alpine
RUN apk add git bash
COPY --from=builder /devstats-minimal/* /usr/bin/
COPY --from=builder /etc/gha2db /etc/gha2db
