FROM nginx
EXPOSE 80
RUN apt update && apt install -y wget
COPY *.svg /usr/share/nginx/html/
COPY images/health/static_page_health_check.sh /usr/bin
COPY index_graphql.html /usr/share/nginx/html/index.html
