FROM golang:1.20.4
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y ca-certificates openssh-client git curl make sudo locales locales-all
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ADD tests/ACCC4CF8.asc .
RUN sudo apt-key add ACCC4CF8.asc
ADD tests/pgdg.list /etc/apt/sources.list.d/pgdg.list
RUN sudo apt update -y && sudo apt -y install postgresql-16 postgresql-client-16
RUN go install golang.org/x/lint/golint@latest && go install golang.org/x/tools/cmd/goimports@latest && go install github.com/jgautheron/goconst/cmd/goconst@latest && go install github.com/jgautheron/usedexports@latest && go install github.com/kisielk/errcheck@latest
ADD tests/test.sh .
CMD ./test.sh
