#!/bin/bash
# Derive the Rust variant of a Go-builder Dockerfile (images/Dockerfile.{full,minimal}.{prod,test}).
# Usage: ./images/rust_dockerfile.sh images/Dockerfile.minimal.test > images/Dockerfile.minimal.test.rust
#
# The Go images clone devstatscode and compile it inside a golang builder stage; the Rust images take the
# static musl binaries pre-built by images/Dockerfile.rust-bins (devstats-bins.tar) and only lay out
# data/binaries with images/Makefile.{full,minimal}.rust - so the builder needs neither Go, git clone nor any
# sources, and the resulting images ship the same runtime content (binaries, /etc/gha2db, devstats data); the Go
# Dockerfiles' clone cleanup step (COPY ... /tmp/tars/ + RUN tar tf ... git ls-files ...) is dropped as there is no clone
# to clean up. Everything else (patch.sh project lists, runtime stage) is kept verbatim so
# there is a single source of truth: the Go Dockerfile. Every expected substitution must happen exactly once,
# otherwise this script fails (structure of the Go Dockerfile changed - update this script).
if [ -z "$1" ] || [ ! -f "$1" ]
then
  echo "$0: usage: $0 images/Dockerfile.{full,minimal}.{prod,test}" >&2
  exit 1
fi
src="$1"
echo "# GENERATED by images/rust_dockerfile.sh from ${src} - do not edit, edit ${src} instead."
echo "# Rust variant: DevStats binaries are the Rust port (devstatscode/rust) built as static musl executables by"
echo "# images/Dockerfile.rust-bins (devstats-bins.tar) instead of Go binaries compiled in a golang builder stage."
awk '
  /^FROM golang:[^ ]* AS builder$/ { print "FROM alpine AS builder"; c["from"]++; next }
  /^RUN apt-get update .* apt-get install -y / { print "RUN apk add --no-cache bash make"; c["apt"]++; next }
  /^RUN git clone https:\/\/github\.com\/cncf\/devstatscode$/ { c["clone"]++; next }
  /^RUN go mod tidy$/ { print "ENV GOPATH=/go"; print "RUN mkdir -p /go/bin"; c["gomod"]++; next }
  /^ADD devstatscode\.tar \.$/ { print "ADD devstats-bins.tar /rust-bins/"; c["code"]++; next }
  /^RUN make -f \.\/images\/Makefile\.(minimal|full) dockerinstall$/ { sub(/ dockerinstall$/, ".rust dockerinstallrust"); print; c["install"]++; next }
  /^RUN make -f \.\/images\/Makefile\.full links$/ { print "RUN make -f ./images/Makefile.full.rust links"; c["links"]++; next }
  /^COPY devstats\.tar devstats-docker-images\.tar \/tmp\/tars\/$/ { c["tarlist"]++; next }
  /^RUN tar tf \/tmp\/tars\/devstats\.tar .* git ls-files .*/ { c["cleanup"]++; next }
  /^RUN go / || /^COPY --from=builder \/go\/bin/ { print "unexpected go-specific line: " $0 > "/dev/stderr"; bad=1; next }
  { print }
  END {
    split("from apt clone gomod code install", need, " ")
    for (i in need) if (c[need[i]] != 1) { print "rust_dockerfile.sh: expected exactly one " need[i] " line, found " c[need[i]]+0 > "/dev/stderr"; bad=1 }
    if (c["links"] > 1) { print "rust_dockerfile.sh: more than one links line" > "/dev/stderr"; bad=1 }
    if (c["tarlist"] > 1 || c["cleanup"] > 1 || c["tarlist"] != c["cleanup"]) { print "rust_dockerfile.sh: expected one COPY ... /tmp/tars/ line and one source cleanup line (or neither)" > "/dev/stderr"; bad=1 }
    if (bad) exit 2
  }
' "$src"
